name: Python Script Workflow

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  run-python-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Default props
        id: default_repo
        run: |
          echo "::set-output name=repo_name::MFE3"
          echo "::set-output name=target_branch::mfe-translations-collection"
          echo "::set-output name=base_target_branch::MFE_en"
          echo "::set-output name=tareget_repo::Intermediate"
        
      - name: Collect PR INFO
        run:
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "$PR_TITLE"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.INTERMEDIATE_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python script
        run: python python.py

      - name: Make the directory
        run: mkdir -p /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}

      - name: Set up Git
        run: |
          git config --global user.name "mamoanwar97-procore"
          git config --global user.email "mahmoud.m.anwar@procore.com"

      - name: Check if branch exists
        id: check_branch
        run: |
          if git ls-remote --exit-code --heads https://github.com/mamoanwar97-procore/${{ steps.default_repo.outputs.tareget_repo }}.git ${{ steps.default_repo.outputs.target_branch }}; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi

      - name: Checkout ${{ steps.default_repo.outputs.tareget_repo }} repo if branch exists
        if: steps.check_branch.outputs.branch_exists == 'true'
        uses: actions/checkout@v3
        with:
          repository: "mamoanwar97-procore/${{ steps.default_repo.outputs.tareget_repo }}"
          token: ${{ secrets.INTERMEDIATE_TOKEN }}
          path: ${{ steps.default_repo.outputs.tareget_repo }}
          ref: ${{ steps.default_repo.outputs.target_branch }}

      - name: Create and checkout branch if it does not exist
        if: steps.check_branch.outputs.branch_exists == 'false'
        uses: actions/checkout@v3
        with:
          repository: "mamoanwar97-procore/${{ steps.default_repo.outputs.tareget_repo }}"
          token: ${{ secrets.INTERMEDIATE_TOKEN }}
          path: ${{ steps.default_repo.outputs.tareget_repo }}
          ref: ${{ steps.default_repo.outputs.base_target_branch }}

      - name: Commit updated translations to ${{ steps.default_repo.outputs.tareget_repo }} repo
        id: push_changes
        run: |
          cd /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}
          if [ "${{ steps.check_branch.outputs.branch_exists }}" == "false" ]; then
            git checkout -b ${{ steps.default_repo.outputs.target_branch }}
          fi
          mkdir -p /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}/${{ steps.default_repo.outputs.repo_name }}
          cp -r /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/translations /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}/${{ steps.default_repo.outputs.repo_name }}
          if [ -n "$(git status --porcelain)" ]; then
            touch temp.yml  # Create temp.yml if it doesn't exist
            cat /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}/pr_info.yml
            cat /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}/pr_info.yml >> temp.yml
            REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
            echo -e "  - repo_name: \"$REPO_NAME\"\n    pr_name: \"${{ github.event.pull_request.title }}\"\n    pr_number: ${{ github.event.pull_request.number }}" >> temp.yml
            mv temp.yml /home/runner/work/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.repo_name }}/${{ steps.default_repo.outputs.tareget_repo }}/pr_info.yml
            git add .
            git commit -m "Update translations ðŸŽ‰"
            git push origin ${{ steps.default_repo.outputs.target_branch }} --force
            echo "::set-output name=new_changes::true"
          else
            echo "No changes to commit"
          fi
    
      - name: Check for existing PR
        id: check_pr
        env: 
          GH_TOKEN: ${{ secrets.INTERMEDIATE_TOKEN }}
        run: |
          PR_EXISTS=$(gh pr list --repo mamoanwar97-procore/${{ steps.default_repo.outputs.tareget_repo }} --head ${{ steps.default_repo.outputs.target_branch }} --state open --json number --jq '.[].number')
          if [ -z "$PR_EXISTS" ]; then
            echo "::set-output name=pr_exists::false"
          else
            echo "::set-output name=pr_exists::true"
          fi

      - name: Open PR
        if: steps.push_changes.outputs.new_changes == 'true' && steps.check_pr.outputs.pr_exists == 'false'
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.INTERMEDIATE_TOKEN }}
          from-branch: ${{ steps.default_repo.outputs.target_branch }}
          to-branch: ${{ steps.default_repo.outputs.base_target_branch }}
          repository-owner: mamoanwar97-procore
          repository: ${{ steps.default_repo.outputs.tareget_repo }}
